version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: app
      POSTGRES_DB: db
